openapi: '3.0.2'
info:
  title: COODFort
  version: '1.0'
servers:
  - url: http://localhost:8000
    description: Local server
components:
  securitySchemes:
    COODFortTGUserId:
      type: apiKey
      in: header
      name: coodfort-tguid
    TGQueryCheckString:
      type: apiKey
      in: header
      name: coodfort-tgquerycheckstring
    COODFortLogin:
      type: apiKey
      in: header
      name: coodfort-login
    COODFortPassword:
      type: apiKey
      in: header
      name: coodfort-password
paths:
  /version:
    get:
      operationId: version
      security: []
      responses:
        '200': 
          description: OK
  /eatery/new:
    post:
      operationId: newEatery
      responses:
        '200':
          description: OK
  /eatery/update:
    post:
      operationId: updateEatery
      responses:
        '200':
          description: OK
  /eatery/view:
    post:
      operationId: viewEatery
      responses:
        '200':
          description: OK
  /eatery/publish:
    post:
      operationId: publishEatery
      responses:
        '200':
          description: OK
  /employee/new:
    post:
      operationId: newEmployee
      security: []      
      responses:
        '200':
          description: OK
  /employee/view:
    post:
      operationId: viewEmployee
      responses:
        '200':
          description: OK
  /meal/new:
    post:
      operationId: newMeal
      security: []      
      responses:
        '200':
          description: OK

security:
  - COODFortTGUserId: []
    TGQueryCheckString: []
  - COODFortLogin: []
    COODFortPassword: []